require 'yaml' 

$user = ENV['USER']
$cfg = YAML.load_file($user + '.cfg')

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws|
    aws.access_key_id 		= $cfg['access_key_id']
    aws.secret_access_key 	= $cfg['secret_access_key']
    aws.keypair_name 		= $cfg['keypair_name']
    aws.ssh_private_key_path 	= $cfg['ssh_private_key_path']

    aws.availability_zone 	= $cfg['availability_zone']
    aws.region 			= $cfg['region']
    aws.instance_type 		= $cfg['instance_type']
    aws.security_groups 	= $cfg['security_groups']

    aws.ami 			= $cfg['ami']
    aws.ssh_username 		= $cfg['ssh_username']
  end
end
